### ISSUE TITLE
Cannot start php api with parallel parameter

### ISSUE THREAD

**Issue by yael-lorenzo** [athena-oss/plugin-php#16]
Running this command

ATHENA_ENV_TARGET_IP=207.97.233.153 ATHENA_ENV_TARGET_DOMAIN=www.letgo.com.ar ATHENA_ENV_TARGET_PROXY=http://athena-plugin-proxy-www.letgo.com.ar ATHENA_ENV_TARGET_REPORT=report_www.letgo.com.ar ATHENA_INSTANCE=www.letgo.com.ar /home/ubuntu/athena/athena php api /home/ubuntu/workspace/Athena/modules/delorean/test-api /home/ubuntu/workspace/Athena/modules/delorean/test-api/athena.json --parallel=2

I get 

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--processes 2" option does not exist.

**Comment by pproenca** [comment]
Hey @yael-lorenzo-olx 

This has been identified as a bug and fixed in https://github.com/athena-oss/plugin-php/commit/597b1b2a35254ca0a5a812d5eb6bbf5ca37a5e6d

We will release this today.

**Comment by ghost** [comment]
@yael-lorenzo-olx Can you please test against master and confirm that it works for you?

**Comment by yael-lorenzo** [comment]
I do not have the same mistake anymore. I have another one regarding the inner architecture of the project with a singleton pattern that does not allow me to run it.

Just for info:
`[RuntimeException]
  The process: '/opt/athena/vendor/bin/phpunit' '--bootstrap' '/opt/athena/bootstrap.php' '--configuration' '/opt/tests/phpunit.xml' '--log-junit' '/tmp/PT_v02GAm' 'naspersclassi
  fieds\regional\delorean\atlas\web\ApiTest\DeloreanTestHandler' '/opt/tests/DeloreanTestHandler.php'
  Log file "/tmp/PT_v02GAm" is empty.
  This means a PHPUnit process was unable to run "/opt/tests/DeloreanTestHandler.php"
  Maybe there is more than one class in this file.`
