### ISSUE TITLE
unknown flag: --link athena-selenium-0-hub:athena-selenium-hub

### ISSUE THREAD

**Issue by fergadipaolx** [athena-oss/plugin-php#24]
Hi guys :)

So I want to run parallel process on my bdd test
I run command `athena selenium start hub latest`
Then `athena selenium start chrome-debug latest -p 9998-9999:5900 --skip-proxy --link-hub=athena-selenium-0-hub --instances=2`
Then `athena info` to check all containers
The result is

> [INFO] Running containers [image|container|status]:

>  * selenium/node-chrome-debug  athena-selenium-0-chrome-debug-1  [UP]  To access it use http://192.168.99.100:9998
>  * selenium/node-chrome-debug  athena-selenium-0-chrome-debug    [UP]  To access it use http://192.168.99.100:9999
>  * selenium/hub                athena-selenium-0-hub             [UP]  To access it use http://192.168.99.100:32776

Then I run command `athena php bdd . athena.bdd.json --config=behat-bdd.yml --parallel-process=2 --browser=chrome`
And the result is

> [INFO] Auto linking with hub container 'athena-selenium-0-hub'...
unknown flag: --link athena-selenium-0-hub:athena-selenium-hub
See 'docker run --help'.

The Athena version is v0.10.3 and PHP version v0.7.2

**Comment by pproenca** [comment]
Hey @fergadipaolx is this still valid?

**Comment by fergadipaolx** [comment]
No, this is not valid anymore, thank you :)

**Comment by pproenca** [comment]
Closing after talking with @fergadipaolx. The cause was a corrupted installation. It's now fixed.
